language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

sudo: false

install:
  - composer install

script:
  - vendor/bin/phpcs --extensions=php -n -s .
